### ISSUE TITLE
v2.0 Roadmap

### ISSUE THREAD

**Issue by adamgruber** [adamgruber/mochawesome#68]
There are some big changes planned for Version 2.0, including:
- [x] Break out the HTML report into a standalone package (_Useful if you already have some saved test output JSON and just want to create the report._)
- [x] Rewrite the report using React components
- [x] Remove Bootstrap and only use select styles as needed
- [x] Remove jQuery
- [x] Add/Enhance tests
- [x] Switch from gulp to webpack
- [x] Rewrite CSS using css-modules and cssnext
- [x] Support showing of diffs
- [x] Support rendering of additional test information
- [x] Updated design

The standalone report package can be found here: [mochawesome-report](https://github.com/adamgruber/mochawesome-report)

**Comment by clouless** [comment]
I really love this tool. But since you seem to go for a big refactoring maybe these features could be nice too (at least I would love them for our customers projects):

  * Custom Theming (provide logo and colors)
  * Disable test-code being included into json (since for closed-source projects we just want to publish test results and not the code)

As far as I understand you are saying with your new project `mochawesome-report` one will be able to only generate the json (and not all the assets)? (that would be really nice)

**Comment by adamgruber** [comment]
@clouless Thanks for the suggestions.

Custom theming is an interesting one but probably not something that will make it into the first releases of v2.

I like the option to disable test code but I'm not sure about leaving it out of the json or just making so it doesn't render in the report.

My thinking is that `mochawesome` will continue to generate the json output and `mochawesome-report` will consume it and produce the html. This way you should be able to generate a report from previously saved json without re-running the tests.

**Comment by clouless** [comment]
sounds great :)

**Comment by ScottFreeCode** [comment]
Given that Mocha already has a JSON reporter (and a TAP reporter), is there a definite need for Mochawesome to output its own JSON format instead of piggy-backing on an existing one?

For that matter, if you could not only piggyback on the existing JSON reporter output but create a general tool to take JSON reporter output and any Mocha reporter and feed the Mocha reporter the same events Mocha would have to generate that JSON output, not only would Mochawesome then be able to report on saved test result data, but any Mocha reporter would be able to.

(We had somebody ask about converting JSON to other report formats recently due to a situation where the tool that used Mocha limited its output to JSON, and frankly being able to do this would make testing reporters way easier since it could be separated from running tests to generate the results.)

(Although, maybe an even better alternative would be to create a serialization format for the [common test reporter interface](https://github.com/js-reporters/js-reporters) so not only would the system work for all Mocha reporters but for all test runners too?)

**Comment by adamgruber** [comment]
@ScottFreeCode I based the JSON output on the built-in JSON reporter but quickly realized that in order to do all the things I wanted Mochawesome to do, I needed to augment the JSON to add properties and relationships that were not in the existing JSON output.

**Comment by ScottFreeCode** [comment]
Interesting -- so the JSON reporter is lossy compared to what Mocha's reporter events originally provide? (I'm not very familiar with the events myself beyond the concept and the fact that there have been efforts to standardize them.)

**Comment by adamgruber** [comment]
The JSON reporter is more selective and basic in the data it outputs. I'm sure it has its uses but it wasn't created to be used as the basis for rendering a full-fledged HTML report.

**Comment by adamgruber** [comment]
Version 2 is out now
